name: day2_trip
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/one.jpg
    - assets/images/two.jpg
    - assets/images/three.jpg
    - assets/images/four.jpg

 # fonts:
    #- family: Nunito
     # fonts:
      #  - asset: assets/fonts/Nunito-Regular.ttf
       # - asset: assets/fonts/Nunito-Black.ttf
        #- asset: assets/fonts/Nunito-Bold.ttf
